In [ ]:
import pandas as pd
import numpy as np

In [ ]:
link_for_importance = "https://ourworldindata.org/grapher/how-important-religion-is-in-your-life.csv?v=1&csvType=full&useColumnShortNames=true"
#path_for_importance = '/content/drive/MyDrive/Colab Notebooks/how-important-religion-is-in-your-life.csv'

importance = pd.read_csv(link_for_importance, storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})
number = pd.read_csv("https://ourworldindata.org/grapher/number-of-people-by-religion.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# 676767676767676767676767676767676767676767676767676767676767676767676767676767676767

# Отобразим первые 5 строк DataFrame, чтобы убедиться, что данные загружены корректно
display(importance.head())
display(number.head())

,entity,code,year,very_important_in_life_religion,rather_important_in_life_religion,not_very_important_in_life_religion,notatall_important_in_life_religion,dont_know_important_in_life_religion,no_answer_important_in_life_religion,very_important_in_life_religion__annotations,rather_important_in_life_religion__annotations,not_very_important_in_life_religion__annotations,notatall_important_in_life_religion__annotations,dont_know_important_in_life_religion__annotations,no_answer_important_in_life_religion__annotations
0,Albania,ALB,1998,24.22422,34.534530,28.228230,10.71071,2.302302,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,2004,27.50000,31.200000,25.200000,14.20000,1.900000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,ALB,2010,15.71519,35.645400,27.452140,18.17237,1.967477,1.047418,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,ALB,2022,24.36961,48.684380,15.685870,10.84857,0.061695,0.349869,NaN,NaN,NaN,NaN,NaN,NaN
4,Algeria,DZA,2004,90.63963,7.488299,0.936037,NaN,0.936037,0.000000,NaN,NaN,NaN,NaN,NaN,NaN

,entity,code,year,count__religion_buddhists,count__religion_hindus,count__religion_muslims,count__religion_jews,count__religion_christians,count__religion_religiously_unaffiliated,count__religion_other_religions
0,Afghanistan,AFG,2010,< 10000,< 10000,28210000,< 10000,30000,< 10000,30000
1,Afghanistan,AFG,2020,< 10000,< 10000,39020000,< 10000,< 10000,< 10000,40000
2,Africa,OWID_AFR,2010,8,134,48085,9,53658,2712,2615
3,Africa,OWID_AFR,2020,10,147,61814,6,70314,3007,2784
4,Albania,ALB,2010,< 10000,< 10000,2050000,< 10000,590000,280000,< 10000

In [ ]:
#( very * 1 + rather* 0.66+ n_very*0.33 + not_imp*0)sum(very+rather+n_very+not)

# Припустимо, ваш датафрейм називається df

# 1. Створюємо список колонок для зручності
cols = [
    'very_important_in_life_religion',
    'rather_important_in_life_religion',
    'not_very_important_in_life_religion',
    'notatall_important_in_life_religion'
]

# 2. Розраховуємо суму (знаменник)
# Використовуємо fillna(0), щоб NaN не зіпсували суму,
# але важливо перевірити, чи не є всі значення в рядку NaN

temp_df = importance[cols].fillna(0)

# Тепер рахуємо за вашою формулою
importance['weighted_religiousness_linear'] = (
    temp_df['very_important_in_life_religion'] * 1 +
    temp_df['rather_important_in_life_religion'] * 0.66 +
    temp_df['not_very_important_in_life_religion'] * 0.33 +
    temp_df['notatall_important_in_life_religion'] * 0
) / temp_df.sum(axis=1)

importance['weighted_religiousness_exp'] = (
    temp_df['very_important_in_life_religion'] * 1 +
    temp_df['rather_important_in_life_religion'] * 0.5 +
    temp_df['not_very_important_in_life_religion'] * 0.1 +
    temp_df['notatall_important_in_life_religion'] * 0
) / temp_df.sum(axis=1)


# Опціонально: якщо row_sum був 0, замінюємо inf на NaN
importance['weighted_religiousness_linear'] = importance['weighted_religiousness'].replace([np.inf, -np.inf], np.nan)
importance['weighted_religiousness_exp'] = importance['weighted_religiousness'].replace([np.inf, -np.inf], np.nan)

In [ ]:
display(importance.head())

,entity,code,year,very_important_in_life_religion,rather_important_in_life_religion,not_very_important_in_life_religion,notatall_important_in_life_religion,dont_know_important_in_life_religion,no_answer_important_in_life_religion,very_important_in_life_religion__annotations,rather_important_in_life_religion__annotations,not_very_important_in_life_religion__annotations,notatall_important_in_life_religion__annotations,dont_know_important_in_life_religion__annotations,no_answer_important_in_life_religion__annotations,weighted_religiousness_linear,weighted_religiousness_exp
0,Albania,ALB,1998,24.22422,34.534530,28.228230,10.71071,2.302302,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.576598,0.453586
1,Albania,ALB,2004,27.50000,31.200000,25.200000,14.20000,1.900000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.575005,0.465036
2,Albania,ALB,2010,15.71519,35.645400,27.452140,18.17237,1.967477,1.047418,NaN,NaN,NaN,NaN,NaN,NaN,0.498018,0.374110
3,Albania,ALB,2022,24.36961,48.684380,15.685870,10.84857,0.061695,0.349869,NaN,NaN,NaN,NaN,NaN,NaN,0.619325,0.504882
4,Algeria,DZA,2004,90.63963,7.488299,0.936037,NaN,0.936037,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.967969,0.953701

In [ ]:
 display(importance[['entity','code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp']].head(10))

,entity,code,year,weighted_religiousness_linear,weighted_religiousness_exp
0,Albania,ALB,1998,0.576598,0.453586
1,Albania,ALB,2004,0.575005,0.465036
2,Albania,ALB,2010,0.498018,0.374110
3,Albania,ALB,2022,0.619325,0.504882
4,Algeria,DZA,2004,0.967969,0.953701
5,Algeria,DZA,2014,0.960117,0.946689
6,Andorra,AND,2010,0.323090,0.217153
7,Andorra,AND,2022,0.342475,0.233633
8,Argentina,ARG,1993,0.632189,0.542369
9,Argentina,ARG,1998,0.630249,0.530607

In [ ]:
# Фільтруємо датафрейм за потрібними роками
years_to_check = [2008, 2009, 2010, 2011, 2012 , 2018, 2019, 2020, 2021, 2022]
filtered_df = importance[importance['year'].isin(years_to_check)]

# Дивимось, скільки унікальних країн є для кожного року
print(filtered_df.groupby('year')['entity'].nunique())

year
2010    81
2022    92
Name: entity, dtype: int64

In [ ]:
url = 'https://fmfi-compbio.github.io/viz/data/World_bank.csv'
countries = pd.read_csv(url).set_index('Country')
display(countries)

,ISO3,Region,Income Group,Population2000,Population2010,Population2020,Area,GDP2000,GDP2010,GDP2020,Expectancy2000,Expectancy2010,Expectancy2020,Fertility2000,Fertility2010,Fertility2020
Country,,,,,,,,,,,,,,,,
Afghanistan,AFG,South Asia,Low income,19542983.0,28189672.0,38972231.0,652860.0,NaN,562.499219,512.055098,55.298000,60.851000,62.575000,7.534,6.099,4.750
Albania,ALB,Europe & Central Asia,Upper middle income,3089026.0,2913021.0,2837849.0,28750.0,1126.683340,4094.349686,5343.037704,75.404000,77.936000,76.989000,2.231,1.656,1.400
Algeria,DZA,Middle East & North Africa,Lower middle income,30774621.0,35856344.0,43451666.0,2381741.0,1780.376063,4495.921476,3354.153164,70.478000,73.808000,74.453000,2.566,2.843,2.942
American Samoa,ASM,East Asia & Pacific,High income,58229.0,54849.0,46189.0,200.0,NaN,10446.863206,15609.777220,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,AND,Europe & Central Asia,High income,66097.0,71519.0,77699.0,470.0,21620.465102,48237.890541,37207.238871,NaN,NaN,NaN,NaN,1.270,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands,VIR,Latin America & Caribbean,High income,108642.0,108356.0,106291.0,350.0,NaN,39905.128418,39411.045254,76.619512,77.865854,79.819512,2.060,2.300,2.030
West Bank and Gaza,PSE,Middle East & North Africa,Upper middle income,2922153.0,3786161.0,4803269.0,6020.0,1476.171850,2557.075624,3233.568638,70.388000,73.004000,74.403000,5.443,4.383,3.570
Yemen,YEM,Middle East & North Africa,Low income,18628701.0,24743945.0,32284046.0,527970.0,519.591639,1249.063085,578.512010,62.588000,67.280000,64.650000,6.318,4.855,3.886
Zambia,ZMB,Sub-Saharan Africa,Lower middle income,9891135.0,13792087.0,18927715.0,752610.0,364.026145,1469.361450,956.831729,45.231000,56.799000,62.380000,5.926,5.363,4.379
Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,11834676.0,12839770.0,15669667.0,390760.0,565.284390,937.840340,1372.696674,44.686000,50.652000,61.124000,3.974,4.025,3.545

In [ ]:
countries_prep = countries.reset_index().rename(columns={'Country': 'entity', 'ISO3': 'code'})

def get_most_recent_year_data(df, primary_year, secondary_year):
    # Get data for the primary target year (e.g., 2022)
    primary_data = df[df['year'] == primary_year].copy()

    # Get data for the secondary target year (e.g., 2020) for entities not covered by the primary year
    secondary_data = df[(df['year'] == secondary_year) & (~df['entity'].isin(primary_data['entity']))].copy()

    # For any remaining entities, find the latest year greater than or equal to the secondary target year
    remaining_entities_df = df[~df['entity'].isin(primary_data['entity']) & ~df['entity'].isin(secondary_data['entity'])]
    latest_other_years = pd.DataFrame()
    if not remaining_entities_df.empty:
        df_after_secondary = remaining_entities_df[remaining_entities_df['year'] >= secondary_year].copy()
        if not df_after_secondary.empty:
            idx = df_after_secondary.groupby('entity')['year'].idxmax()
            latest_other_years = df_after_secondary.loc[idx].copy()

    # Combine all datasets, ensuring unique entities and prioritizing by year preference
    final_data = pd.concat([primary_data, secondary_data, latest_other_years]).drop_duplicates(subset='entity', keep='first')
    return final_data

### Таблица 1: Актуальная важность религии по группам доходов (не раньше 2020 года)

Эта таблица показывает наиболее актуальные данные по важности религии для каждой страны, исключая данные ранее 2020 года, и сопоставляет их с группой доходов страны.

In [ ]:
# Create a copy to avoid SettingWithCopyWarning
importance_copy = importance.copy()

# Filter for years 2020 and onwards
recent_importance = importance_copy[importance_copy['year'] >= 2020]

# For each entity, get the row with the maximum year within the recent_importance filtered data
# This handles cases where both 2020 and 2022 data might exist, picking the latest.
idx = recent_importance.groupby('entity')['year'].idxmax()
latest_data_importance_filtered = recent_importance.loc[idx]

# Merge with countries data
table1 = pd.merge(latest_data_importance_filtered, countries_prep, on='code', how='inner')

# Select and display relevant columns for Table 1
table1.reset_index()
table1 = table1[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'Income Group']]
display(table1.head())

,entity_x,code,year,weighted_religiousness_linear,weighted_religiousness_exp,Income Group
0,Albania,ALB,2022,0.619325,0.504882,Upper middle income
1,Andorra,AND,2022,0.342475,0.233633,High income
2,Argentina,ARG,2022,0.571411,0.450700,Upper middle income
3,Armenia,ARM,2022,0.782043,0.706915,Upper middle income
4,Australia,AUS,2022,0.337753,0.247009,High income

### Таблица 2: Тенденции ВВП и важности религии

Эта таблица показывает тенденции ВВП и уровни важности религии для стран в 2010 году и в наиболее актуальный год (приоритет 2022, затем 2020), а также изменения между этими периодами.

In [ ]:
# Get 2010 data
importance_2010 = importance[importance['year'] == 2010].copy()

# Get 2022/2020 data (prioritizing 2022)
importance_202x = get_most_recent_year_data(importance, 2022, 2020)

# Merge 2010 data with countries
merged_2010_gdp = pd.merge(importance_2010, countries_prep, on='code', how='inner')
merged_2010_gdp = merged_2010_gdp[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'GDP2010']]
merged_2010_gdp = merged_2010_gdp.rename(columns={
    'year': 'year_2010',
    'weighted_religiousness_linear': 'religiousness_linear_2010',
    'weighted_religiousness_exp': 'religiousness_exp_2010',
    'GDP per capita': 'GDP_2010'
})

# Merge 202x data with countries
merged_202x_gdp = pd.merge(importance_202x, countries_prep, on='code', how='inner')
merged_202x_gdp = merged_202x_gdp[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'GDP2020']]
merged_202x_gdp = merged_202x_gdp.rename(columns={
    'year': 'year_202x',
    'weighted_religiousness_linear': 'religiousness_linear_202x',
    'weighted_religiousness_exp': 'religiousness_exp_202x',
    'GDP per capita': 'GDP_202x'
})

# Combine the two dataframes based on 'entity' and 'code'
table2 = pd.merge(merged_2010_gdp, merged_202x_gdp, on=['entity_x', 'code'], how='inner')

# Calculate trends
table2['GDP_Change'] = table2['GDP2020'] - table2['GDP2010']
table2['Religiousness_Linear_Change'] = table2['religiousness_linear_202x'] - table2['religiousness_linear_2010']
table2['Religiousness_Exp_Change'] = table2['religiousness_exp_202x'] - table2['religiousness_exp_2010']

display(table2.head())

,entity_x,code,year_2010,religiousness_linear_2010,religiousness_exp_2010,GDP2010,year_202x,religiousness_linear_202x,religiousness_exp_202x,GDP2020,GDP_Change,Religiousness_Linear_Change,Religiousness_Exp_Change
0,Albania,ALB,2010,0.498018,0.374110,4094.349686,2022,0.619325,0.504882,5343.037704,1248.688018,0.121307,0.130772
1,Andorra,AND,2010,0.323090,0.217153,48237.890541,2022,0.342475,0.233633,37207.238871,-11030.651670,0.019385,0.016480
2,Argentina,ARG,2010,0.624363,0.518117,10385.964432,2022,0.571411,0.450700,8500.837939,-1885.126493,-0.052952,-0.067417
3,Armenia,ARM,2010,0.754047,0.663473,3143.029480,2022,0.782043,0.706915,4505.867742,1362.838262,0.027996,0.043442
4,Australia,AUS,2010,0.429065,0.325296,52147.024194,2022,0.337753,0.247009,51868.247557,-278.776638,-0.091313,-0.078287

### Таблица 3: Тенденции ожидаемой продолжительности жизни и важности религии

Эта таблица показывает тенденции ожидаемой продолжительности жизни и уровни важности религии для стран в 2010 году и в наиболее актуальный год (приоритет 2022, затем 2020), а также изменения между этими периодами.

In [ ]:
# Get 2010 data
importance_2010 = importance[importance['year'] == 2010].copy()

# Get 2022/2020 data (prioritizing 2022)
importance_202x = get_most_recent_year_data(importance, 2022, 2020)

# Merge 2010 data with countries
merged_2010_le = pd.merge(importance_2010, countries_prep, on='code', how='inner')
merged_2010_le = merged_2010_le[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'Expectancy2010']]
merged_2010_le = merged_2010_le.rename(columns={
    'year': 'year_2010',
    'weighted_religiousness_linear': 'religiousness_linear_2010',
    'weighted_religiousness_exp': 'religiousness_exp_2010',
    'Life Expectancy': 'Life_Expectancy_2010'
})

# Merge 202x data with countries
merged_202x_le = pd.merge(importance_202x, countries_prep, on='code', how='inner')
merged_202x_le = merged_202x_le[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'Expectancy2020']]
merged_202x_le = merged_202x_le.rename(columns={
    'year': 'year_202x',
    'weighted_religiousness_linear': 'religiousness_linear_202x',
    'weighted_religiousness_exp': 'religiousness_exp_202x',
    'Life Expectancy': 'Life_Expectancy_202x'
})

# Combine the two dataframes based on 'entity' and 'code'
table3 = pd.merge(merged_2010_le, merged_202x_le, on=['entity_x', 'code'], how='inner')

# Calculate trends
table3['Life_Expectancy_Change'] = table3['Expectancy2020'] - table3['Expectancy2010']
table3['Religiousness_Linear_Change'] = table3['religiousness_linear_202x'] - table3['religiousness_linear_2010']
table3['Religiousness_Exp_Change'] = table3['religiousness_exp_202x'] - table3['religiousness_exp_2010']

display(table3.head())

,entity_x,code,year_2010,religiousness_linear_2010,religiousness_exp_2010,Expectancy2010,year_202x,religiousness_linear_202x,religiousness_exp_202x,Expectancy2020,Life_Expectancy_Change,Religiousness_Linear_Change,Religiousness_Exp_Change
0,Albania,ALB,2010,0.498018,0.374110,77.936000,2022,0.619325,0.504882,76.989,-0.947000,0.121307,0.130772
1,Andorra,AND,2010,0.323090,0.217153,NaN,2022,0.342475,0.233633,NaN,NaN,0.019385,0.016480
2,Argentina,ARG,2010,0.624363,0.518117,75.721000,2022,0.571411,0.450700,75.892,0.171000,-0.052952,-0.067417
3,Armenia,ARM,2010,0.754047,0.663473,73.160000,2022,0.782043,0.706915,72.173,-0.987000,0.027996,0.043442
4,Australia,AUS,2010,0.429065,0.325296,81.695122,2022,0.337753,0.247009,83.200,1.504878,-0.091313,-0.078287

### Таблица 4: Тенденции фертильности и важности религии

Эта таблица показывает тенденции фертильности и уровни важности религии для стран в 2010 году и в наиболее актуальный год (приоритет 2022, затем 2020), а также изменения между этими периодами.

In [ ]:
# Get 2010 data
importance_2010 = importance[importance['year'] == 2010].copy()

# Get 2022/2020 data (prioritizing 2022)
importance_202x = get_most_recent_year_data(importance, 2022, 2020)

# Merge 2010 data with countries
merged_2010_fert = pd.merge(importance_2010, countries_prep, on='code', how='inner')
merged_2010_fert = merged_2010_fert[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'Fertility2010']]
merged_2010_fert = merged_2010_fert.rename(columns={
    'year': 'year_2010',
    'weighted_religiousness_linear': 'religiousness_linear_2010',
    'weighted_religiousness_exp': 'religiousness_exp_2010',
    'Fertility rate': 'Fertility_rate_2010'
})

# Merge 202x data with countries
merged_202x_fert = pd.merge(importance_202x, countries_prep, on='code', how='inner')
merged_202x_fert = merged_202x_fert[['entity_x', 'code', 'year', 'weighted_religiousness_linear', 'weighted_religiousness_exp', 'Fertility2020']]
merged_202x_fert = merged_202x_fert.rename(columns={
    'year': 'year_202x',
    'weighted_religiousness_linear': 'religiousness_linear_202x',
    'weighted_religiousness_exp': 'religiousness_exp_202x',
    'Fertility rate': 'Fertility_rate_202x'
})

# Combine the two dataframes based on 'entity' and 'code'
table4 = pd.merge(merged_2010_fert, merged_202x_fert, on=['entity_x', 'code'], how='inner')

# Calculate trends
table4['Fertility_rate_Change'] = table4['Fertility2020'] - table4['Fertility2010']
table4['Religiousness_Linear_Change'] = table4['religiousness_linear_202x'] - table4['religiousness_linear_2010']
table4['Religiousness_Exp_Change'] = table4['religiousness_exp_202x'] - table4['religiousness_exp_2010']

display(table4.head())

,entity_x,code,year_2010,religiousness_linear_2010,religiousness_exp_2010,Fertility2010,year_202x,religiousness_linear_202x,religiousness_exp_202x,Fertility2020,Fertility_rate_Change,Religiousness_Linear_Change,Religiousness_Exp_Change
0,Albania,ALB,2010,0.498018,0.374110,1.656,2022,0.619325,0.504882,1.400,-0.256,0.121307,0.130772
1,Andorra,AND,2010,0.323090,0.217153,1.270,2022,0.342475,0.233633,NaN,NaN,0.019385,0.016480
2,Argentina,ARG,2010,0.624363,0.518117,2.346,2022,0.571411,0.450700,1.911,-0.435,-0.052952,-0.067417
3,Armenia,ARM,2010,0.754047,0.663473,1.501,2022,0.782043,0.706915,1.575,0.074,0.027996,0.043442
4,Australia,AUS,2010,0.429065,0.325296,1.928,2022,0.337753,0.247009,1.581,-0.347,-0.091313,-0.078287

In [ ]:
# мульти-релігійність Х політ стабільність і тд

In [ ]:
display(importance.head())
display(number.head())

,entity,code,year,very_important_in_life_religion,rather_important_in_life_religion,not_very_important_in_life_religion,notatall_important_in_life_religion,dont_know_important_in_life_religion,no_answer_important_in_life_religion,very_important_in_life_religion__annotations,rather_important_in_life_religion__annotations,not_very_important_in_life_religion__annotations,notatall_important_in_life_religion__annotations,dont_know_important_in_life_religion__annotations,no_answer_important_in_life_religion__annotations,weighted_religiousness,weighted_religiousness_linear,weighted_religiousness_exponential,weighted_religiousness_exp
0,Albania,ALB,1998,24.22422,34.534530,28.228230,10.71071,2.302302,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.576598,0.576598,0.453586,0.576598
1,Albania,ALB,2004,27.50000,31.200000,25.200000,14.20000,1.900000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.575005,0.575005,0.465036,0.575005
2,Albania,ALB,2010,15.71519,35.645400,27.452140,18.17237,1.967477,1.047418,NaN,NaN,NaN,NaN,NaN,NaN,0.498018,0.498018,0.374110,0.498018
3,Albania,ALB,2022,24.36961,48.684380,15.685870,10.84857,0.061695,0.349869,NaN,NaN,NaN,NaN,NaN,NaN,0.619325,0.619325,0.504882,0.619325
4,Algeria,DZA,2004,90.63963,7.488299,0.936037,NaN,0.936037,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.967969,0.967969,0.953701,0.967969

,entity,code,year,count__religion_buddhists,count__religion_hindus,count__religion_muslims,count__religion_jews,count__religion_christians,count__religion_religiously_unaffiliated,count__religion_other_religions
0,Afghanistan,AFG,2010,< 10000,< 10000,28210000,< 10000,30000,< 10000,30000
1,Afghanistan,AFG,2020,< 10000,< 10000,39020000,< 10000,< 10000,< 10000,40000
2,Africa,OWID_AFR,2010,8,134,48085,9,53658,2712,2615
3,Africa,OWID_AFR,2020,10,147,61814,6,70314,3007,2784
4,Albania,ALB,2010,< 10000,< 10000,2050000,< 10000,590000,280000,< 10000

In [ ]:
#карта
import plotly.express as px


# Припустимо, що df вже містить колонку 'weighted_religiousness'
# Також розрахуємо загальну кількість людей для відсотків
religion_cols = ['count__religion_buddhists', 'count__religion_hindus', 'count__religion_muslims', 'count__religion_jews', 'count__religion_christians', 'count__religion_religiously_unaffiliated', 'count__religion_other_religions']

# Convert religion count columns to numeric, coercing errors to NaN and then filling NaN with 0
for col in religion_cols:
    number[col] = pd.to_numeric(number[col], errors='coerce').fillna(0)

# 1. Рахуємо сумарне населення (всі релігії), щоб отримати відсотки
number['total_population'] = number[religion_cols].sum(axis=1)

# Merge 'number' with 'importance' to get 'weighted_religiousness_linear'
# assuming 'entity', 'code', and 'year' are common keys
merged_df = pd.merge(number, importance[['entity', 'code', 'year', 'weighted_religiousness_linear']],
                     on=['entity', 'code', 'year'], how='left')

# Define human-readable names for religions
religion_name_map = {
    'count__religion_buddhists': 'Буддисти',
    'count__religion_hindus': 'Індуси',
    'count__religion_muslims': 'Мусульмани',
    'count__religion_jews': 'Євреї',
    'count__religion_christians': 'Християни',
    'count__religion_religiously_unaffiliated': 'Не релігійні',
    'count__religion_other_religions': 'Інші релігії'
}

# Create a new column for custom, sorted hover text
merged_df['custom_hover_info'] = ''

for index, row in merged_df.iterrows():
    religion_percentages_list = []
    for rel_base_col in religion_cols:
        # Calculate percentage for the current religion in the current row
        total_pop = row['total_population']
        rel_count = row[rel_base_col]

        if pd.isna(total_pop) or total_pop == 0:
            percent_value = np.nan
        else:
            percent_value = (rel_count / total_pop) * 100

        human_name = religion_name_map.get(rel_base_col, rel_base_col)
        religion_percentages_list.append({'name': human_name, 'value': percent_value})

    # Filter out NaN percentages and sort by value descending
    # Also, filter to include only percentages > 0
    sorted_percentages = sorted(
        [item for item in religion_percentages_list if not pd.isna(item['value']) and item['value'] > 0],
        key=lambda x: x['value'],
        reverse=True
    )

    # Format into a string for hover tooltip
    if sorted_percentages:
        # Include a header for clarity
        hover_lines = ['<b>Релігійний склад:</b>'] + [f"{item['name']}: {item['value']:.1f}%" for item in sorted_percentages]
        merged_df.loc[index, 'custom_hover_info'] = '<br>'.join(hover_lines)
    else:
        merged_df.loc[index, 'custom_hover_info'] = 'Дані про релігійний склад відсутні.'


# 3. Будуємо карту
fig = px.choropleth(
    merged_df, # Use the merged DataFrame
    locations="code", # Corrected to lowercase 'code'
    color="weighted_religiousness_linear",  # Твоя нова фіча
    hover_name="entity", # Corrected to lowercase 'entity'
    # Додаємо код, саму метрику та всі відсотки релігій
    hover_data={
        "code": True, # Corrected to lowercase 'code'
        "weighted_religiousness_linear": ":.2f" # формат до 2 знаків
        # "custom_hover_info": True # Removed as requested
    },
    title="World Religiousness Index by Country (2010)",
    color_continuous_scale="Viridis", # Змінив на Viridis, щоб краще було видно градієнт 0...1
    range_color=[0, 1],
    labels={'weighted_religiousness_linear': 'Загальна релігійсність'} # Rename label for the color bar
)

# Re-add custom hover info to display religions, as it was removed unintentionally
# The previous implementation was adding it correctly as a separate hover_data item
# I will re-add it explicitly as a custom data and use the text argument of choropleth
# to allow for rich custom hover text while keeping the other hover_data items.
fig.update_traces(customdata=merged_df[['custom_hover_info']],
                  hovertemplate='<b>%{hover_name}</b><br>Code: %{location}<br>Загальна релігійсність: %{z:.2f}<br>%{customdata[0]}')

# Трохи підправимо вигляд, щоб карта була на весь екран
fig.update_layout(margin={"r":0,"t":50,"l":0,"b":0})
fig.show()